[package]
name = "chromecast-experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
rust_cast = "0.19.0"
serde_json = "1.0.140"
tokio = { version = "1.45.0", features = ["full"] }
tower-http = { version = "0.6.3", features = ["fs"] }
